# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

from collections.abc import Callable

def html_escape(text: str) -> str: ...
def no_escape(text: str) -> str: ...

class HandlebarrzTemplate:
    def __init__(self) -> None: ...

    # Strict mode
    def get_strict_mode(self) -> bool: ...
    def set_strict_mode(self, enabled: bool) -> None: ...

    # Dev mode
    def get_dev_mode(self) -> bool: ...
    def set_dev_mode(self, enabled: bool) -> None: ...

    # Escape function
    def set_escape_fn(self, escape_fn: str) -> None: ...

    # Template registration
    def register_template(self, name: str, template_string: str) -> None: ...
    def register_partial(self, name: str, template_string: str) -> None: ...
    def register_template_file(self, name: str, file_path_str: str) -> None: ...
    def register_templates_directory(
        self, dir_path_str: str, extension: str
    ) -> None: ...

    # Helper registration
    def register_helper(
        self, name: str, helper_fn: Callable[[str], str]
    ) -> None: ...

    # Template management
    def has_template(self, name: str) -> bool: ...
    def unregister_template(self, name: str) -> None: ...

    # Rendering
    def render(self, name: str, data_json: str) -> str: ...
    def render_template(self, template_str: str, data_json: str) -> str: ...

    # Extra helper registration
    def register_extra_helpers(self) -> None: ...
