#!/usr/bin/env bash
#
# Format all files in the project
#
# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

#set -x  # Uncomment to enable tracing.
set -euo pipefail

if ((EUID == 0)); then
  echo "Please do not run as root"
  exit
fi

TOP_DIR=$(git rev-parse --show-toplevel)

# Add license header to all files that don't already have it.
"${TOP_DIR}/scripts/add_license"

# Format all TOML files.
"${TOP_DIR}/scripts/format_toml_files"
if [[ $? -ne 0 ]]; then
  exit 1
fi

# Format all Python code and organize imports.
uv run --directory "${TOP_DIR}/python" ruff check --select I --fix --preview --unsafe-fixes .
uv run --directory "${TOP_DIR}/python" ruff format --preview .
if [[ $? -ne 0 ]]; then
  exit 1
fi

# Format all Go code.
go mod -C "${TOP_DIR}/go" tidy
go fmt -C "${TOP_DIR}/go" ./...
if [[ $? -ne 0 ]]; then
  exit 1
fi

# Format all TypeScript code.
pushd ${TOP_DIR}
pnpm run format
if [[ $? -ne 0 ]]; then
  exit 1
fi
popd

# Format all rust code
pushd "${TOP_DIR}/python/handlebarrz"
cargo fmt --all
if [[ $? -ne 0 ]]; then
  exit 1
fi
popd
