#!/usr/bin/env bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

#set -x  # Uncomment to enable tracing.
set -euo pipefail

if ((EUID == 0)); then
  echo "Please do not run as root"
  exit
fi

GO_VERSION="1.23.8"

TOP_DIR=$(git rev-parse --show-toplevel)

# Add license header to all files that don't already have it.
"${TOP_DIR}/scripts/add_license"

if command -v rust-parallel >/dev/null 2>&1; then
  echo "Using rust-parallel to format files in parallel"
  printf "%s\n" \
    "${TOP_DIR}/scripts/format_go_files" \
    "${TOP_DIR}/scripts/format_java_files" \
    "${TOP_DIR}/scripts/format_rust_files" \
    "${TOP_DIR}/scripts/format_python_files" \
    "${TOP_DIR}/scripts/format_handlebarrz_files" \
    "${TOP_DIR}/scripts/format_toml_files" \
    "${TOP_DIR}/scripts/format_ts_files" \
    | rust-parallel -s --exit-on-error || exit 1
else
  echo "rust-parallel was not detected; not performing formatting in parallel"
  "${TOP_DIR}/scripts/format_go_files" || exit 1
  "${TOP_DIR}/scripts/format_java_files" || exit 1
  "${TOP_DIR}/scripts/format_python_files" || exit 1
  "${TOP_DIR}/scripts/format_handlebarrz_files" || exit 1
  "${TOP_DIR}/scripts/format_rust_files" || exit 1
  "${TOP_DIR}/scripts/format_toml_files" || exit 1
  "${TOP_DIR}/scripts/format_ts_files" || exit 1
fi

# Do this after all of the above have completed.
"${TOP_DIR}/scripts/format_build_files" || exit 1
