#!/usr/bin/env bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

#set -x  # Uncomment to enable tracing.
set -euo pipefail

if ((EUID == 0)); then
  echo "Please do not run as root"
  exit
fi

GO_VERSION="1.23.8"

TOP_DIR=$(git rev-parse --show-toplevel)

# Add license header to all files that don't already have it.
"${TOP_DIR}/scripts/add_license"

# Format all TOML files.
"${TOP_DIR}/scripts/format_toml_files"
if [[ $? -ne 0 ]]; then
  exit 1
fi

# Format all Python code and organize imports.
uv run --directory "${TOP_DIR}/python" ruff check --select I --fix --preview --unsafe-fixes .
uv run --directory "${TOP_DIR}/python" ruff format --preview .
if [[ $? -ne 0 ]]; then
  exit 1
fi

# Format all Go code.
go mod -C "${TOP_DIR}/go" tidy -go="${GO_VERSION}"
go fmt -C "${TOP_DIR}/go" ./...
if [[ $? -ne 0 ]]; then
  exit 1
fi

# Format all TypeScript code.
pushd ${TOP_DIR}
pnpm run format
if [[ $? -ne 0 ]]; then
  exit 1
fi
popd

# Format all rust code
pushd "${TOP_DIR}/python/handlebarrz"
cargo fmt --all
if [[ $? -ne 0 ]]; then
  exit 1
fi
popd
