#!/usr/bin/env bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

#set -x  # Uncomment to enable tracing.
set -euo pipefail

if ((EUID == 0)); then
  echo "Please do not run as root"
  exit
fi

GO_VERSION="1.23.8"

TOP_DIR=$(git rev-parse --show-toplevel)
GO_DIR="$TOP_DIR/go"

# Modernize and format all Go code.
go mod -C "${GO_DIR}" tidy -go="${GO_VERSION}" || exit 1
go fmt -C "${GO_DIR}" ./... || exit 1
