#!/usr/bin/env bash
#
# Run tests for all supported Python versions
#
# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

TOP_DIR=$(git rev-parse --show-toplevel)
PYTHON_DIR="${TOP_DIR}/python"
PYTHON_VERSIONS=(
  "python3.12"
  "python3.13"
  # TODO: Wait for https://github.com/PyO3/pyo3/issues/5000 to be fixed.
  #"python3.14" # Next version to catch breakages early.
)

echo "=== Running Python tests ==="
echo "Project root: ${TOP_DIR}"
echo "Python directory: ${PYTHON_DIR}"
echo ""

# WORKAROUND:
#
# error: the configured Python interpreter version (3.14) is newer than PyO3's
# maximum supported version (3.13)
#
#  = help: please check if an updated version of PyO3 is available. Current
#  version: 0.24.0
#  = help: set PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 to suppress this check and
#  build anyway using the stable ABI
export PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1

pushd "${PYTHON_DIR}"
for VERSION in "${PYTHON_VERSIONS[@]}"; do
  # NOTE: Build the Rust extension for a specific Python version in an isolated
  # virtual environment; otherwise we see weird missing import errors.
  echo "Creating virtual environment for ${VERSION}..."
  uv venv --python "${VERSION}"
  uv run --python "${VERSION}" --active --directory handlebarrz maturin develop
  echo "Running tests with Python ${VERSION}..."
  uv run \
    --python "${VERSION}" \
    --active \
    pytest -vv --log-level=DEBUG .
  echo "Cleaning up virtual environment for ${VERSION}..."
  rm -rf .venv
done
popd

echo "=== Python tests completed ==="

exit $?
