#!/usr/bin/env bash
#
# Run tests for all supported Python versions
#
# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

TOP_DIR=$(git rev-parse --show-toplevel)
PYTHON_DIR="${TOP_DIR}/python"
PYTHON_VERSIONS=(
  "python3.12"
  "python3.13"
)

echo "=== Running Python tests ==="
echo "Project root: ${TOP_DIR}"
echo "Python directory: ${PYTHON_DIR}"
echo ""

pushd "${PYTHON_DIR}"
for VERSION in "${PYTHON_VERSIONS[@]}"; do
  echo "Running tests with Python ${VERSION}..."
  # NOTE: Build the Rust extension for a specific Python version; otherwise we
  # see weird missing import errors.
  uv run --python "${VERSION}" --directory handlebarrz maturin develop
  uv run \
    --python "${VERSION}" \
    pytest -vv --log-level=DEBUG .
done
popd

echo "=== Python tests completed ==="

exit $?
