#!/usr/bin/env bash
#
# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

TOP_DIR=$(git rev-parse --show-toplevel)

GO_DIR="${TOP_DIR}/go"
PY_DIR="${TOP_DIR}/python"
JS_DIR="${TOP_DIR}/js"

pushd "${GO_DIR}" &>/dev/null
golangci-lint run ./...
go vet -v ./...
popd &>/dev/null

# TODO: Disabled for now since we have a lot of lint errors.
#pnpm run lint

uv run --directory "${PY_DIR}" ruff check --select I --fix --preview --unsafe-fixes .
uv run --directory "${PY_DIR}" mypy .
