#!/usr/bin/env bash
#
# Run tests for all supported Go versions
#
# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

TOP_DIR=$(git rev-parse --show-toplevel)

# We're concerned about only the release versions of Go, not "tip", but it has
# been included as an example in case it is needed in the future.
GO_VERSIONS=(
  "1.22.12"
  "1.23.6"
  "1.24.0"
  #"tip" # Fetches and builds the latest version of go from source and is slow.
)

cd "${TOP_DIR}/go"

for VERSION in "${GO_VERSIONS[@]}"; do
  echo "Running tests with Go ${VERSION}..."
  pushd "${TOP_DIR}/go" &>/dev/null
  # Ensure that the build works too.
  "${TOP_DIR}/scripts/golang" "${VERSION}" build ./...
  # Run the tests.
  "${TOP_DIR}/scripts/golang" "${VERSION}" test -coverprofile=coverage.out ./...
  # Print the coverage report.
  "${TOP_DIR}/scripts/golang" "${VERSION}" tool cover -func=coverage.out

  # Check the coverage threshold.
  # TODO: Make this portable.
  #
  #COVERAGE=$(go test ./... -cover | grep "coverage:" | awk '{print $5}' | tr -d '%')
  #THRESHOLD=80
  #if [[ $(echo "$COVERAGE $THRESHOLD" | awk '{print ($1 >= $2)}') -eq 1 ]]; then
  #  echo "Coverage is $COVERAGE%, which meets the threshold of $THRESHOLD%."
  #  exit 0
  #else
  #  echo "Coverage is $COVERAGE%, which is below the threshold of $THRESHOLD%."
  #  exit 1
  #fi

  popd &>/dev/null
done
exit $?
