#!/usr/bin/env bash
#
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# Builds and tests the Bazel project.
# Installs bazelisk and buildifier if they are not found.

set -euo pipefail

if ! command -v "bazelisk" >/dev/null 2>&1; then
  echo "Bazelisk not found. Installing via go install..."
  go install github.com/bazelbuild/bazelisk@latest
fi

TOP_DIR=$(git rev-parse --show-toplevel)

echo "Updating build files..."
"${TOP_DIR}/scripts/gazelle"

echo "Pinning dependencies..."
bazelisk run @maven//:pin

echo "Running Bazel build (Java 21)..."
bazelisk build --config=java21 //...

echo "Running Bazel tests (Java 21)..."
bazelisk test --config=java21 //... --test_output=errors

#echo "Running Bazel build (Java 17)..."
#bazelisk build --config=java17 //...
#
#echo "Running Bazel tests (Java 17)..."
#bazelisk test --config=java17 //... --test_output=errors

echo "Bazel build and tests completed successfully."
