#!/usr/bin/env bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Run tests for all supported Python versions using tox

set -euo pipefail

if ((EUID == 0)); then
  echo "Please do not run as root"
  exit 1
fi

TOP_DIR=$(git rev-parse --show-toplevel)
PY_DIR="$TOP_DIR/python"

echo "Running Python tests via tox..."

# Erase any previous coverage data to prevent errors during combine
echo "Erasing previous coverage data..."
uv run --active --directory "$PY_DIR" coverage erase || echo "Coverage erase failed (maybe no data existed?), continuing..."
rm -rf "${PY_DIR}"/.coverage*

# Build the handlebarrz package.
uv run --active --directory "$PY_DIR/handlebarrz" maturin develop

# Use uv run to execute tox, passing the --parallel flag to tox
# The '-p auto' flag tells tox to use available CPU cores for parallelism.
# Any arguments passed to this script ($@) are forwarded to tox (and then pytest)
uv run --active --directory "$PY_DIR" tox "$@"
