#!/usr/bin/env bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

TOP_DIR=$(git rev-parse --show-toplevel)
GO_DIR="${TOP_DIR}/go"

# We're concerned about only the release versions of Go, not "tip", but it has
# been included as an example in case it is needed in the future.
GO_VERSIONS=(
  "1.23.8"
  "1.24.2"
  #"tip" # Fetches and builds the latest version of go from source and is slow.
)

echo "=== Running Go tests ==="
echo "Project root: ${TOP_DIR}"
echo "Go directory: ${GO_DIR}"
echo ""

pushd "${GO_DIR}"
for VERSION in "${GO_VERSIONS[@]}"; do
  echo "Running tests with Go ${VERSION}..."
  # Ensure that the build works too.
  "${TOP_DIR}/scripts/golang" "${VERSION}" build ./...
  # Run the tests.
  "${TOP_DIR}/scripts/golang" "${VERSION}" test -coverprofile=coverage.out ./...
  # Print the coverage report.
  "${TOP_DIR}/scripts/golang" "${VERSION}" tool cover -func=coverage.out

  # Check the coverage threshold.
  # TODO: Make this portable.
  #
  #COVERAGE=$(go test ./... -cover | grep "coverage:" | awk '{print $5}' | tr -d '%')
  #THRESHOLD=80
  #if [[ $(echo "$COVERAGE $THRESHOLD" | awk '{print ($1 >= $2)}') -eq 1 ]]; then
  #  echo "Coverage is $COVERAGE%, which meets the threshold of $THRESHOLD%."
  #  exit 0
  #else
  #  echo "Coverage is $COVERAGE%, which is below the threshold of $THRESHOLD%."
  #  exit 1
  #fi
done
popd

echo "=== Go tests completed ==="

exit $?
