#!/usr/bin/env bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

if ((EUID == 0)); then
  echo "Please do not run as root"
  exit 1
fi

TOP_DIR=$(git rev-parse --show-toplevel)

"${TOP_DIR}/scripts/run_go_tests"
if [ $? -ne 0 ]; then
  echo "Go tests failed."
  exit 1
fi

"${TOP_DIR}/scripts/run_rust_checks"
if [ $? -ne 0 ]; then
  echo "Rust tests failed."
  exit 1
fi

"${TOP_DIR}/scripts/run_handlebarrz_tests"
if [ $? -ne 0 ]; then
  echo "Handlebarrz tests failed."
  exit 1
fi

"${TOP_DIR}/scripts/run_python_tests"
if [ $? -ne 0 ]; then
  echo "Python tests failed."
  exit 1
fi

"${TOP_DIR}/scripts/run_js_tests"
if [ $? -ne 0 ]; then
  echo "JavaScript tests failed."
  exit 1
fi

exit $?
